test_array:
			 java -cp .:overseer.jar com.ullink.perf.myths.ListIteration array 0


test_linked:
				java -cp .:overseer.jar com.ullink.perf.myths.ListIteration linked 0


#https://jpbempel.github.io/2013/12/17/arraylist-vs-linkedlist.html
