


all:
				cc -o test -O0 -fverbose-asm -fno-dwarf2-cfi-asm -fno-stack-protector gets.c

without:
				cc -S  -O0 -fverbose-asm -fno-dwarf2-cfi-asm gets.c



asm:
				cc  -S -fverbose-asm -fno-dwarf2-cfi-asm -fno-stack-protector gets.c
